### ISSUE TITLE
Update 'Embedded Linux 6.3.0' on README

### ISSUE THREAD

**Issue by leonheldattoradex** [toradex/meta-toradex-security#10]
README.md says 

> This layer only works on Embedded Linux 6.3.0 and newer releases.

I suggest replacing "Embedded Linux 6.3.0 and newer releases" to "Toradex Embedded Linux BSP Layers 6.3.0 and Torizon OS 6.3.0 and newer releases" which is more or less what the official documentation uses [0][1]

[0] https://developer.toradex.com/linux-bsp/os-development/build-yocto/yocto-project/
[1] https://developer.toradex.com/torizon/torizoncore/torizoncore-upgrade-notes/

**Comment by sergioprado** [comment]
@leonheldattoradex looks good! Would you mind sending a PR for this?
