### ISSUE TITLE
Display warnings on bootloader commands that wouldn't be allowed on closed state

### ISSUE THREAD

**Issue by rborn-tx** [toradex/meta-toradex-security#23]
The whitelisting feature implemented as part of our U-Boot hardening features works like this:

- If the device is **open** and the command passes the whitelist for the **open** state accept/execute the command without messages; if the command does not pass the said whitelist show a warning and do not execute the command.
- If the device is **closed** and the command passes the whitelist for the **closed** state accept/execute the command without messages; if the command does not pass the said whitelist show a warning and do not execute the command.

To detect situations where a new command is added to the boot script that would prevent boot after the device is closed, it would be useful to show a warning in the following situation:

- If the device is **open** and the command does not pass the whitelist for the **closed** state.

We might consider showing the message only on the first N occurrences to avoid bloating the logs.

Having this improvement should avoid the situation that was reported in issue #20.

**Comment by MMG-DG** [comment]
+1 from me for this.
I have jumped onto something else, but will be back looking at this soon as I don't believe I see any issues in my current setup without changing the open config to be the same as the closed config.
