### ISSUE TITLE
Does this layer do something to remove the USB gadget device?

### ISSUE THREAD

**Issue by MMG-DG** [toradex/meta-toradex-security#40]
I am not sure if there is something being set in my related security layer or if it is this layer.
But when I build with this security layer it appears that I loose the following devices, configs and drivers in the built image:

- usbg - usb0 ethernet over usb
- wlan0 - wifi
- uap0 - I believe this is either a wifi-ap or bluetooth device

I have stripped all my changes back as much as possible and am doing nothing but removing USB, DHCP and WIFI from the u-boot-toradex build, so not sure why the linux kernel now doesn't show them.
It did a while back and have not noticed this change until now.

Could it be the removal of WIFI and USB from the u-boot causing this?
I am using the following in a kernel config:
```
CONFIG_CMD_BOOTEFI=n
CONFIG_CMD_BOOTEFI_BOOTMGR=n
CONFIG_CMD_USB=n
CONFIG_USB_STORAGE=n
CONFIG_CMD_NET=n
CONFIG_CMD_DHCP=n
```
And I have a custom patch that allows for removing the items from the boot script:
```
From 83f045bbd428dc968cad82e51c8a3945127371aa Mon Sep 17 00:00:00 2001
From: John Doe <johndoe@example.com>
Date: Thu, 25 Apr 2024 12:48:48 +0100
Subject: [PATCH] Removing insecure boot args from verdin config

---
 include/configs/verdin-imx8mp.h | 15 +++++++++++++--
 1 file changed, 13 insertions(+), 2 deletions(-)

diff --git a/include/configs/verdin-imx8mp.h b/include/configs/verdin-imx8mp.h
index 88299ad950b..194c2b43649 100644
--- a/include/configs/verdin-imx8mp.h
+++ b/include/configs/verdin-imx8mp.h
@@ -58,11 +58,16 @@
 	"scriptaddr=0x50280000\0"
 
 /* Enable Distro Boot */
+#ifdef CONFIG_CMD_DHCP
+#define BOOT_TARGET_DEVICE_DHCP(func) func(DHCP, dhcp, na)
+#else
+#define BOOT_TARGET_DEVICE_DHCP(func)
+#endif
 #ifndef CONFIG_SPL_BUILD
 #define BOOT_TARGET_DEVICES(func) \
 	func(MMC, mmc, 1) \
 	func(MMC, mmc, 2) \
-	func(DHCP, dhcp, na)
+	BOOT_TARGET_DEVICE_DHCP(func)
 #include <config_distro_bootcmd.h>
 #undef CONFIG_ISO_PARTITION
 #else
@@ -75,13 +80,19 @@
 #  define BOOT_SCRIPT	"boot.scr"
 #endif
 
+#ifdef CONFIG_CMD_DHCP
+#define BOOT_SCRIPT_DHCP "boot_script_dhcp=" BOOT_SCRIPT "\0"
+#else
+#define BOOT_SCRIPT_DHCP
+#endif
+
 /* Initial environment variables */
 #define CONFIG_EXTRA_ENV_SETTINGS \
 	BOOTENV \
 	MEM_LAYOUT_ENV_SETTINGS \
 	"boot_file=Image\0" \
 	"boot_scripts=" BOOT_SCRIPT "\0" \
-	"boot_script_dhcp=" BOOT_SCRIPT "\0" \
+	BOOT_SCRIPT_DHCP \
 	"console=ttymxc2\0" \
 	"fdt_board=dev\0" \
 	"initrd_addr=0x43800000\0" \
-- 
2.34.1
```

**Comment by sergioprado** [comment]
@MMG-DG this layer does not touch any device driver or hardware related configuration. We only enable a few additional options in the kernel depending on the security feature enabled by the user.

Also, I have here a build running on Verdin iMX8MP, and the wlan0 and uap0 are visible to me.

Maybe it is something related to your setup? Can you run '`bitbake virtual/kernel -c savedefconfig`' with and without this layer to compare the configs?

**Comment by MMG-DG** [comment]
I didn't think so, but just wanted to check before I dive down the rabbit hole of locating the cause. My guess is that some of the base packages are being excluded somehow. I believe it is the mwifiexap package that is missing.

Will double check today and post here if I find anything.

**Comment by MMG-DG** [comment]
Please feel free to close this issue. Not sure what happened but my latest image is now working fine again. Would appear that it was originally missing the usbgx config package to provide the g1.schema file. Don't recall adding anything to fix this, but apparently it is now working fine.
