### ISSUE TITLE
Remove hard dependencies on `meta-toradex-nxp` and `meta-toradex-ti`

### ISSUE THREAD

**Issue by tjallingt** [toradex/meta-toradex-security#50]
Hi, we'd like to use this layer in our custom yocto setup for the `verdin-am62`.
Currently to use this layer for the `am62` board we would need to install both the `meta-toradex-nxp` and `meta-toradex-ti` layers.
Since we build only for the ti board it seems silly to include a layer for the nxp based boards.
As far as I can tell all the board specific stuff is already located in `dynamic-layers` and only included conditionally based on the presence of either of these layers.

Would it be possible to move both of these to `LAYERRECOMMENDS` instead?

**Comment by rborn-tx** [comment]
Closing this since the proposed fix was merged.
